# Generated by Django 5.0.6 on 2024-07-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_informations_delete_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('image', models.ImageField(default='default_image.png', upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000000)),
            ],
        ),
    ]
